spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/websocket
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  data:
    mongodb:
      uri: mongodb://localhost:27017/websocket

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true #show sql
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

  mvc: # swagger로 인해서 세팅
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    include: API-KEY

#  openai:
#    api-key: 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

chatgpt:
  api-key: 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


logging.level:
  org.hibernate.SQL: DEBUG

# S3 image upload setting
cloud:
  aws:
    credentials:
      accessKey: AKIARNYJE4X55QI7TB6F
      secretKey: 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
    s3:
      bucket: bonobono
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
