server:
  port: 8081

spring:
  profiles:
    include:
      - oauth
      - cloud

#  datasource:
#    url: jdbc:mariadb://localhost:3306/bonobono
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 1234
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/websocket

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true #show sql
    defer-datasource-initialization: true

## Spring Boot 실행시 SQL문 자동실행
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  token:
    secret-key: q1w2e3r4
#    secret-key: ${JWT_SECRET_KEY} # q1w2e3r4

logging.level:
  org.hibernate.SQL: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
