server:
  port: 8081

spring:
  profiles:
    include:
      - prod

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          time_zone : Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    time-zone: Asia/Seoul

logging.level:
  org.hibernate.SQL: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
