spring:
  oauth2:
    google:
      client-id: 138071912923-rukbjge64dvj8obia6regv65ih23i6ad.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/member/login/google/callback
      authorization-grant-type: authorization_code
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    kakao:
      client-id: 3ce82c17073f38a7ed03b44959660240
      client-secret: YBSbf7ADkjXW5ZKCcJ8hBKSm8BMhstu9
      redirect-uri: http://localhost:8080/member/login/kakao/callback
      client-authentication-method: POST
      authorization-grant-type: authorization_code
      scope: profile_nickname, profile_image, account_email
      client-name: Kakao
    naver:
      client-id: aWaYoWqq2RFRAszNidzw
      client-secret: kNznxXbrwF
      redirect-uri: http://localhost:8080/member/login/naver/callback
      authorization-grant-type: authorization_code
      scope: name, email, profile_image
      client-name: Naver
  provider:
    google:
      authorization_uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
      token_uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    kakao:
      authorization_uri: https://kauth.kakao.com/oauth/authorize
      token_uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user_name_attribute: id
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: response