server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mariadb://localhost:3306/Bonobono
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org.hibernate:
#      type.descriptor.sql: trace
#      SQL: debug

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}